### ISSUE TITLE
How to add new pair?

### ISSUE THREAD

**Issue by amitsharma8891** [gitbitex/gitbitex-spot#14]
Hi,

I was trying to add a new pair, but could not do any transaction. Can anyone tell what is the step by step procedure to add a new pair?

Thanks

**Comment by lxlmjjay** [comment]
I had the same problem

**Comment by greensheng** [comment]
insert into `g_product`(`id`,`created_at`,`updated_at`,`base_currency`,`quote_currency`,`base_min_size`,`base_max_size`,`base_scale`,`quote_scale`,`quote_increment`,`quote_min_size`,`quote_max_size`) values
('BCH-USDT',null,null,'BCH','USDT',0.0000100000000000,10000.0000000000000000,4,2,0.01,0E-16,0E-16),
('BTC-USDT',null,null,'BTC','USDT',0.0000100000000000,10000000.0000000000000000,6,2,0.01,0E-16,0E-16),
('EOS-USDT',null,null,'EOS','USDT',0.0001000000000000,1000.0000000000000000,4,3,0,0E-16,0E-16),
('ETH-USDT',null,null,'ETH','USDT',0.0001000000000000,10000.0000000000000000,4,2,0.01,0E-16,0E-16),
('LTC-USDT',null,null,'LTC','USDT',0.0010000000000000,1000.0000000000000000,4,2,0.01,0E-16,0E-16);

**You need to restart gitbitex spot after adding a new currency pair, because there is no automatic refresh currently**

**Comment by amitsharma8891** [comment]
Yes, after restart it's working as expected :)
